# This workflow will build docker containers and publish them to Google Container Registry
#

name: Build and Publish to GCR - DEV

on:
  push:
    branches:
      # - master
      - develop
      # - k8s-istio-opa

# Environment variables available to all jobs and steps in this workflow
env:
  GCP_PROJECT: wellostack
  #   GCP_EMAIL: ${{ secrets.WELLOSTACK_SA_EMAIL }}
  # GITHUB_SHA: ${{ github.sha }}
  TAG: ${{ github.sha }}
  # TAG: latest
  # TAG: dev
#   GKE_ZONE: us-west1-a
#   GKE_CLUSTER: example-gke-cluster
#   IMAGE: gke-test

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.WELLOSTACK_SA_EMAIL }}
          service_account_key: ${{ secrets.WELLOSTACK_SA_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build
        run: |
          docker-compose -f docker-compose.build.yaml build
          TAG=dev docker-compose -f docker-compose.build.yaml build
        # TAG=latest docker-compose -f docker-compose.build.yaml build

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker-compose -f docker-compose.build.yaml push
          TAG=dev docker-compose -f docker-compose.build.yaml push
        # TAG=latest docker-compose -f docker-compose.build.yaml push